CREATE TABLE IF NOT EXISTS boundary_points (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    zone_id UUID REFERENCES zones(id),
    point_id UUID REFERENCES points(id)
);
