truncate table owned_inventory_items;
alter table owned_inventory_items drop constraint fk_owned_inventory_items_inventory_item_id;
alter table owned_inventory_items drop column inventory_item_id;
alter table owned_inventory_items add column inventory_item_id integer;
