ALTER TABLE users
DROP COLUMN IF EXISTS date_of_birth,
DROP COLUMN IF EXISTS gender,
DROP COLUMN IF EXISTS latitude,
DROP COLUMN IF EXISTS longitude,
DROP COLUMN IF EXISTS location_address,
DROP COLUMN IF EXISTS bio;

