alter table point_of_interest_challenges drop column inventory_item_id;
alter table point_of_interest_challenges add column inventory_item_id uuid;
alter table point_of_interest_challenges add constraint fk_point_of_interest_challenges_inventory_item_id foreign key (inventory_item_id) references inventory_items(id);