ALTER TABLE user_statuses
ADD COLUMN damage_per_tick INTEGER NOT NULL DEFAULT 0,
ADD COLUMN last_tick_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE monster_statuses
ADD COLUMN damage_per_tick INTEGER NOT NULL DEFAULT 0,
ADD COLUMN last_tick_at TIMESTAMP WITH TIME ZONE;
