ALTER TABLE points_of_interest
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE quests
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE challenges
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE scenarios
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE expositions
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE monsters
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE monster_encounters
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE treasure_chests
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE healing_fountains
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE resources
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE movement_patterns
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';

ALTER TABLE inventory_items
  ADD COLUMN IF NOT EXISTS zone_kind TEXT NOT NULL DEFAULT '';
