package generate

import (
	"fmt"
	"math"
	"strings"
)

// BgiCardTray is a freestanding, open-top card well for board-game insert
// sets (bgi-site's second product vertical) — a single well sized to hold
// cardCount cards at a given sleeve thickness, with a finger-scoop cutout
// along one edge so cards can be lifted out (R-2.3). It shares nothing with
// FragRack/LidClip/ShelfRack except the interface — same independence
// principle ShelfRack's own doc comment states.
//
// The module doesn't know it's holding "208 Terraforming Mars project
// cards" — only "hold N cards of this thickness" — exactly like FragRack
// doesn't know about tank gallons. go/pkg/reef/set's assembler is what
// turns a real component count into a cardCount parameter, searching for
// the fewest trays whose stacked height fits a target box.
//
// Printed with the well's floor against the bed (no overhang, no
// supports); the open top faces up in both printing and final use.
type BgiCardTray struct{}

func (BgiCardTray) Slug() string    { return "bgi_card_tray" }
func (BgiCardTray) Version() string { return "v1" }

const (
	bgiCardTrayFloorThicknessMm = 2.0
	bgiCardTrayWallThicknessMm  = 2.0
	bgiCardTrayClearanceMm      = 1.0 // per side, so sleeved cards don't bind
	bgiCardTrayScoopRadiusMm    = 18.0
	bgiCardTrayScoopHeadroomMm  = 15.0 // extra well depth so the scoop can reach under the top card
)

// bgiCardTrayLayout is every dimension SCAD() and Analyze() both need,
// computed once so the two can never quietly disagree about the geometry —
// same reasoning as fragRackLayout/shelfRackLayout.
type bgiCardTrayLayout struct {
	cardWidthMm          float64
	cardHeightMm         float64
	cardCount            int
	totalCardThicknessMm float64
	wellDepthMm          float64
	outerWidthMm         float64
	outerHeightMm        float64
	outerDepthMm         float64
}

func bgiCardTrayParamsToLayout(params map[string]interface{}) (bgiCardTrayLayout, error) {
	var l bgiCardTrayLayout
	var err error

	if l.cardWidthMm, err = paramFloat(params, "cardWidthMm"); err != nil {
		return l, err
	}
	if l.cardHeightMm, err = paramFloat(params, "cardHeightMm"); err != nil {
		return l, err
	}
	cardCountF, err := paramFloat(params, "cardCount")
	if err != nil {
		return l, err
	}
	if l.totalCardThicknessMm, err = paramFloat(params, "totalCardThicknessMm"); err != nil {
		return l, err
	}

	l.cardCount = int(math.Round(cardCountF))
	if l.cardCount < 1 {
		return l, fmt.Errorf("generate/bgi_card_tray: cardCount must be >= 1")
	}
	if l.totalCardThicknessMm <= 0 {
		return l, fmt.Errorf("generate/bgi_card_tray: totalCardThicknessMm must be > 0")
	}

	l.wellDepthMm = float64(l.cardCount)*l.totalCardThicknessMm + bgiCardTrayScoopHeadroomMm
	l.outerWidthMm = l.cardWidthMm + 2*(bgiCardTrayClearanceMm+bgiCardTrayWallThicknessMm)
	l.outerHeightMm = l.cardHeightMm + 2*(bgiCardTrayClearanceMm+bgiCardTrayWallThicknessMm)
	l.outerDepthMm = l.wellDepthMm + bgiCardTrayFloorThicknessMm

	return l, nil
}

func (b BgiCardTray) SCAD(params map[string]interface{}, detail Detail) (string, error) {
	l, err := bgiCardTrayParamsToLayout(params)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	fmt.Fprintf(&buf, "// generated by reef-site generate.BgiCardTray %s — do not hand-edit\n", b.Version())
	fmt.Fprintf(&buf, "$fn = %d;\n\n", detail.fn())
	fmt.Fprintf(&buf, "outer_width_mm = %s;\n", fnum(l.outerWidthMm))
	fmt.Fprintf(&buf, "outer_height_mm = %s;\n", fnum(l.outerHeightMm))
	fmt.Fprintf(&buf, "outer_depth_mm = %s;\n", fnum(l.outerDepthMm))
	fmt.Fprintf(&buf, "floor_thickness_mm = %s;\n", fnum(bgiCardTrayFloorThicknessMm))
	fmt.Fprintf(&buf, "wall_thickness_mm = %s;\n", fnum(bgiCardTrayWallThicknessMm))
	fmt.Fprintf(&buf, "well_width_mm = %s;\n", fnum(l.cardWidthMm+2*bgiCardTrayClearanceMm))
	fmt.Fprintf(&buf, "well_height_mm = %s;\n", fnum(l.cardHeightMm+2*bgiCardTrayClearanceMm))
	fmt.Fprintf(&buf, "well_depth_mm = %s;\n", fnum(l.wellDepthMm))
	fmt.Fprintf(&buf, "scoop_radius_mm = %s;\n\n", fnum(bgiCardTrayScoopRadiusMm))

	buf.WriteString(bgiCardTraySCADBody)
	return buf.String(), nil
}

// Analyze computes structural facts analytically from the same layout math
// SCAD() uses. HeightMm is the tray's own physical height (outerDepthMm) —
// go/pkg/reef/set reads this to search for the fewest trays that fit a
// target box depth, without rendering anything.
func (b BgiCardTray) Analyze(params map[string]interface{}) (Analysis, error) {
	l, err := bgiCardTrayParamsToLayout(params)
	if err != nil {
		return Analysis{}, err
	}

	return Analysis{
		MinWallMm:         math.Min(bgiCardTrayFloorThicknessMm, bgiCardTrayWallThicknessMm),
		HasInternalCavity: true,  // the well is a cavity...
		SealedVoid:        false, // ...but it's open-top by construction, genuinely not sealed
		DrainPathMm:       0,     // not applicable — an open top is its own drain
		HeightMm:          l.outerDepthMm,
	}, nil
}

// ValidateParams catches a well depth that would already blow the shared
// print-envelope limit before ever paying for a render — same reasoning as
// FragRack/ShelfRack's own ValidateParams. 210mm is reef's existing
// MaxBboxMm default; bgi's own config-driven threshold is the real gate at
// the API layer, this is a cheap sanity floor shared across every caller
// regardless of config.
const bgiCardTrayMaxHeightMm = 210.0

func (b BgiCardTray) ValidateParams(params map[string]interface{}) error {
	l, err := bgiCardTrayParamsToLayout(params)
	if err != nil {
		return err
	}
	if l.outerDepthMm > bgiCardTrayMaxHeightMm {
		return fmt.Errorf(
			"cardCount %d at this sleeve thickness needs a %.0fmm-tall tray, over the %.0fmm print envelope — reduce cards per tray (more trays) or use a thinner sleeve class.",
			l.cardCount, l.outerDepthMm, bgiCardTrayMaxHeightMm,
		)
	}
	return nil
}

// bgiCardTraySCADBody is the fixed CSG program; every dimension is a
// variable assigned above so the geometry is entirely parametric. The well
// and scoop cutouts are unioned before the single subtraction against the
// solid outer box, same batching reasoning as FragRack/ShelfRack's bodies.
const bgiCardTraySCADBody = `
module finger_scoop() {
    translate([outer_width_mm / 2, wall_thickness_mm, outer_depth_mm])
        rotate([0, 90, 0])
            cylinder(r = scoop_radius_mm, h = outer_width_mm, center = true);
}

module card_tray() {
    difference() {
        cube([outer_width_mm, outer_height_mm, outer_depth_mm]);

        union() {
            translate([wall_thickness_mm, wall_thickness_mm, floor_thickness_mm])
                cube([well_width_mm, well_height_mm, well_depth_mm + 1]);

            finger_scoop();
        }
    }
}

card_tray();
`
