package generate

import (
	"fmt"
	"math"
	"strings"
)

// FragRack is the hero configurator (Catalog 1.1 / R-4.2): a two-part
// magnetic rack — an inner plate (frag-plug holes + magnet pockets) that
// sits inside the tank, and an outer plate (matching magnet pockets) that
// sits outside the glass. They snap together magnetically across the glass;
// "no assembly beyond inserting purchased magnets" (R-1.3) means the
// customer press-fits two magnets per pocket pair after printing, nothing
// more. Both parts are laid out on one plate so slicing produces one job.
type FragRack struct{}

func (FragRack) Slug() string    { return "frag_rack" }
func (FragRack) Version() string { return "v1" }

// Fixed, "standard purchased magnet" dimensions (R-1.3) — small disc
// magnets, the most common commodity size for this kind of hardware.
const (
	fragMagnetDiameterMm  = 10.0
	fragMagnetThicknessMm = 3.0
	fragMagnetToleranceMm = 0.3

	fragRackThicknessMm = 6.0
	fragOuterPlateDepth = 26.0
	fragTierSpacingMm   = 24.0
	fragTopMarginMm     = 14.0
	fragBottomMarginMm  = 10.0
	fragPlateGapMm      = 14.0
	// fragMinEdgeWallMm is the wall left between a hole's edge and the
	// nearest part edge or the back face of a magnet pocket, in the
	// nominal (non-degenerate) layout.
	fragMinEdgeWallMm = 3.0

	// R-5.3: every internal cavity needs a drain path of at least 4mm so it
	// can't trap air. Magnet pockets are blind holes; each gets a vent
	// channel to the nearest edge so no sealed void can form once a magnet
	// is pressed in.
	fragVentDiameterMm = 2.0
	fragVentLengthMm   = 6.0 // > REEF_MIN_DRAIN_PATH_MM's 4mm default
)

// fragRackLayout is every dimension SCAD() and Analyze() both need,
// computed once so the two can never quietly disagree about the geometry.
type fragRackLayout struct {
	widthMm             float64
	glassThicknessMm    float64
	tierCount           int
	holesPerTier        int
	plugHoleDiameterMm  float64
	rackHeightMm        float64
	plugEdgeMarginMm    float64
	magnetEdgeMarginMm  float64
	magnetCount         int
	magnetDiameterMm    float64
	magnetPocketDepthMm float64
}

func fragRackParamsToLayout(params map[string]interface{}) (fragRackLayout, error) {
	var l fragRackLayout
	var err error

	if l.glassThicknessMm, err = paramFloat(params, "glassThicknessMm"); err != nil {
		return l, err
	}
	tierCountF, err := paramFloat(params, "tierCount")
	if err != nil {
		return l, err
	}
	if l.widthMm, err = paramFloat(params, "widthMm"); err != nil {
		return l, err
	}
	if l.plugHoleDiameterMm, err = paramFloat(params, "plugHoleDiameterMm"); err != nil {
		return l, err
	}
	holesPerTierF, err := paramFloat(params, "holesPerTier")
	if err != nil {
		return l, err
	}

	l.tierCount = int(math.Round(tierCountF))
	l.holesPerTier = int(math.Round(holesPerTierF))
	if l.tierCount < 1 || l.holesPerTier < 1 {
		return l, fmt.Errorf("generate/frag_rack: tierCount and holesPerTier must be >= 1")
	}

	l.rackHeightMm = fragTopMarginMm + fragBottomMarginMm + float64(l.tierCount-1)*fragTierSpacingMm + fragTierSpacingMm/2
	// The edge margin must scale with the hole it's protecting — a fixed
	// margin sized for a 15mm plug hole would let a 20mm hole punch through
	// the part's edge. See generate package tests for the regression this
	// guards against.
	l.plugEdgeMarginMm = l.plugHoleDiameterMm/2 + fragMinEdgeWallMm
	l.magnetDiameterMm = fragMagnetDiameterMm + fragMagnetToleranceMm
	l.magnetEdgeMarginMm = l.magnetDiameterMm/2 + fragMinEdgeWallMm
	l.magnetPocketDepthMm = fragMagnetThicknessMm + fragMagnetToleranceMm

	l.magnetCount = l.tierCount + 1
	if l.magnetCount < 2 {
		l.magnetCount = 2
	}

	return l, nil
}

func (l fragRackLayout) plugHoleSpacingMm() float64 {
	if l.holesPerTier <= 1 {
		return 0
	}
	return (l.widthMm - 2*l.plugEdgeMarginMm) / float64(l.holesPerTier-1)
}

func (l fragRackLayout) magnetSpacingMm() float64 {
	if l.magnetCount <= 1 {
		return 0
	}
	return (l.widthMm - 2*l.magnetEdgeMarginMm) / float64(l.magnetCount-1)
}

func (f FragRack) SCAD(params map[string]interface{}, detail Detail) (string, error) {
	l, err := fragRackParamsToLayout(params)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// generated by reef-site generate.FragRack %s — do not hand-edit\n", f.Version())
	fmt.Fprintf(&b, "$fn = %d;\n\n", detail.fn())
	fmt.Fprintf(&b, "width_mm = %s;\n", fnum(l.widthMm))
	fmt.Fprintf(&b, "rack_height_mm = %s;\n", fnum(l.rackHeightMm))
	fmt.Fprintf(&b, "rack_thickness_mm = %s;\n", fnum(fragRackThicknessMm))
	fmt.Fprintf(&b, "glass_thickness_mm = %s;\n", fnum(l.glassThicknessMm))
	fmt.Fprintf(&b, "plug_hole_d = %s;\n", fnum(l.plugHoleDiameterMm))
	fmt.Fprintf(&b, "plug_edge_margin_mm = %s;\n", fnum(l.plugEdgeMarginMm))
	fmt.Fprintf(&b, "tier_count = %d;\n", l.tierCount)
	fmt.Fprintf(&b, "holes_per_tier = %d;\n", l.holesPerTier)
	fmt.Fprintf(&b, "tier_spacing_mm = %s;\n", fnum(fragTierSpacingMm))
	fmt.Fprintf(&b, "top_margin_mm = %s;\n", fnum(fragTopMarginMm))
	fmt.Fprintf(&b, "magnet_edge_margin_mm = %s;\n", fnum(l.magnetEdgeMarginMm))
	fmt.Fprintf(&b, "magnet_d = %s;\n", fnum(l.magnetDiameterMm))
	fmt.Fprintf(&b, "magnet_h = %s;\n", fnum(l.magnetPocketDepthMm))
	fmt.Fprintf(&b, "magnet_count = %d;\n", l.magnetCount)
	fmt.Fprintf(&b, "vent_d = %s;\n", fnum(fragVentDiameterMm))
	fmt.Fprintf(&b, "vent_len = %s;\n", fnum(fragVentLengthMm))
	fmt.Fprintf(&b, "outer_plate_depth_mm = %s;\n", fnum(fragOuterPlateDepth))
	fmt.Fprintf(&b, "plate_gap_mm = %s;\n\n", fnum(fragPlateGapMm))

	b.WriteString(fragRackSCADBody)
	return b.String(), nil
}

// Analyze computes structural facts analytically from the same layout math
// SCAD() uses (R-5.2/R-5.3) — see the Module.Analyze doc comment for why
// this doesn't inspect the mesh.
func (f FragRack) Analyze(params map[string]interface{}) (Analysis, error) {
	l, err := fragRackParamsToLayout(params)
	if err != nil {
		return Analysis{}, err
	}

	minWall := fragRackThicknessMm // the plate's own thickness, away from any hole

	if l.holesPerTier > 1 {
		plugWall := l.plugHoleSpacingMm() - l.plugHoleDiameterMm
		minWall = math.Min(minWall, plugWall)
	}
	if l.magnetCount > 1 {
		magnetWall := l.magnetSpacingMm() - l.magnetDiameterMm
		minWall = math.Min(minWall, magnetWall)
	}
	// Material left under a magnet pocket, between the pocket floor and the
	// opposite face.
	minWall = math.Min(minWall, fragRackThicknessMm-l.magnetPocketDepthMm)

	return Analysis{
		MinWallMm:         minWall,
		HasInternalCavity: true,  // magnet pockets are blind-hole cavities
		SealedVoid:        false, // every magnet pocket is vented to the top edge, by construction
		DrainPathMm:       fragVentLengthMm,
	}, nil
}

// MaxHolesPerTier is R-4.2's "Upper bound derived from width_mm" — exposed
// so the API layer can recompute and clamp the same way the generator will
// interpret the value, per R-4.5's server-authoritative derived parameters.
func FragRackMaxHolesPerTier(widthMm, plugHoleDiameterMm float64) int {
	edgeMargin := plugHoleDiameterMm/2 + fragMinEdgeWallMm
	usable := widthMm - 2*edgeMargin
	if usable <= 0 {
		return 1
	}
	minSpacing := plugHoleDiameterMm + fragMinEdgeWallMm
	max := int(math.Floor(usable/minSpacing)) + 1
	if max < 1 {
		max = 1
	}
	return max
}

// fragRackSCADBody is the fixed CSG program; every dimension is a variable
// assigned above so the geometry is entirely parametric. Magnet pockets are
// blind holes on the mating faces with a vent channel to the top edge so no
// cavity is ever sealed (R-5.3). Everything is built from cubes/cylinders
// with `difference()` and `hull()`-free unions so it prints flat, on its
// back face, without supports.
const fragRackSCADBody = `
module magnet_pocket(vent_to_top) {
    cylinder(d = magnet_d, h = magnet_h + 0.01);
    if (vent_to_top) {
        translate([0, magnet_d / 2 - 0.01, magnet_h / 2])
            rotate([-90, 0, 0])
                cylinder(d = vent_d, h = vent_len);
    }
}

module magnet_row(y, z_from_face, vent_to_top) {
    spacing = magnet_count > 1 ? (width_mm - 2 * magnet_edge_margin_mm) / (magnet_count - 1) : 0;
    for (i = [0 : magnet_count - 1]) {
        x = magnet_count > 1
            ? magnet_edge_margin_mm + i * spacing
            : width_mm / 2;
        translate([x, y, z_from_face])
            magnet_pocket(vent_to_top);
    }
}

module inner_rack() {
    difference() {
        cube([width_mm, rack_height_mm, rack_thickness_mm]);

        // Frag-plug holes, evenly spaced per tier, drilled straight through.
        for (t = [0 : tier_count - 1]) {
            tier_y = top_margin_mm + t * tier_spacing_mm;
            hole_spacing = holes_per_tier > 1
                ? (width_mm - 2 * plug_edge_margin_mm) / (holes_per_tier - 1)
                : 0;
            for (h = [0 : holes_per_tier - 1]) {
                hole_x = holes_per_tier > 1
                    ? plug_edge_margin_mm + h * hole_spacing
                    : width_mm / 2;
                translate([hole_x, tier_y, -0.5])
                    cylinder(d = plug_hole_d, h = rack_thickness_mm + 1);
            }
        }

        // Magnet pockets on the back face (away from the tank interior),
        // vented to the top edge.
        translate([0, 0, rack_thickness_mm - magnet_h])
            magnet_row(rack_height_mm - top_margin_mm / 2, 0, true);
    }
}

module outer_plate() {
    difference() {
        cube([width_mm, outer_plate_depth_mm, rack_thickness_mm]);

        // Matching magnet pockets on the front face (facing the glass /
        // inner rack), vented to the top edge.
        magnet_row(outer_plate_depth_mm - outer_plate_depth_mm / 2, -0.01, true);
    }
}

inner_rack();
translate([0, rack_height_mm + plate_gap_mm, 0])
    outer_plate();
`

func fnum(f float64) string {
	return fmt.Sprintf("%.4f", f)
}
