package generate

import (
	"fmt"
	"math"
	"strings"
)

// ShelfRack is a freestanding frag rack (R-1.1's pattern extended to a third
// mounting style): a flat deck of frag-plug holes standing on four printed
// legs, for tanks/sumps/shelves where there's no accessible glass to clip a
// magnetic rack to. It shares nothing with FragRack or LidClip except the
// interface — same independence principle LidClip's own doc comment states.
//
// Deck holes go straight through (no blind pockets, unlike FragRack's vented
// magnet pockets), so there is no internal cavity at all and R-5.3's
// sealed-void rule never applies here, the same way it never applies to
// LidClip's open C-mouth.
//
// Printed with the deck against the bed and the four legs extruding straight
// up (no overhang, no supports); the customer flips it over after printing
// so the legs stand on the tank floor/shelf and the deck holds plugs
// elevated above it.
type ShelfRack struct{}

func (ShelfRack) Slug() string    { return "shelf_rack" }
func (ShelfRack) Version() string { return "v1" }

const (
	shelfDeckThicknessMm = 4.0
	shelfLegSizeMm       = 8.0 // square leg cross-section
	shelfLegEdgeOffsetMm = 6.0 // gap between a deck edge and the nearest leg face
	shelfMinEdgeWallMm   = 3.0
)

// shelfRackLayout is every dimension SCAD() and Analyze() both need, computed
// once so the two can never quietly disagree about the geometry — same
// reasoning as fragRackLayout.
type shelfRackLayout struct {
	widthMm            float64
	depthMm            float64
	legHeightMm        float64
	plugHoleDiameterMm float64
	holesPerRow        int
	rowCount           int
	colEdgeMarginMm    float64
	rowEdgeMarginMm    float64
}

func shelfRackParamsToLayout(params map[string]interface{}) (shelfRackLayout, error) {
	var l shelfRackLayout
	var err error

	if l.widthMm, err = paramFloat(params, "widthMm"); err != nil {
		return l, err
	}
	if l.depthMm, err = paramFloat(params, "depthMm"); err != nil {
		return l, err
	}
	if l.legHeightMm, err = paramFloat(params, "legHeightMm"); err != nil {
		return l, err
	}
	if l.plugHoleDiameterMm, err = paramFloat(params, "plugHoleDiameterMm"); err != nil {
		return l, err
	}
	holesPerRowF, err := paramFloat(params, "holesPerRow")
	if err != nil {
		return l, err
	}
	rowCountF, err := paramFloat(params, "rowCount")
	if err != nil {
		return l, err
	}

	l.holesPerRow = int(math.Round(holesPerRowF))
	l.rowCount = int(math.Round(rowCountF))
	if l.holesPerRow < 1 || l.rowCount < 1 {
		return l, fmt.Errorf("generate/shelf_rack: holesPerRow and rowCount must be >= 1")
	}
	if l.legHeightMm <= 0 {
		return l, fmt.Errorf("generate/shelf_rack: legHeightMm must be > 0")
	}

	// Same edge-wall reasoning as FragRack's plugEdgeMarginMm: the margin
	// must scale with the hole it's protecting on both axes independently,
	// since width and depth are packed with holes/rows separately.
	l.colEdgeMarginMm = l.plugHoleDiameterMm/2 + shelfMinEdgeWallMm
	l.rowEdgeMarginMm = l.plugHoleDiameterMm/2 + shelfMinEdgeWallMm

	return l, nil
}

func (l shelfRackLayout) holeSpacingXMm() float64 {
	if l.holesPerRow <= 1 {
		return 0
	}
	return (l.widthMm - 2*l.colEdgeMarginMm) / float64(l.holesPerRow-1)
}

func (l shelfRackLayout) holeSpacingYMm() float64 {
	if l.rowCount <= 1 {
		return 0
	}
	return (l.depthMm - 2*l.rowEdgeMarginMm) / float64(l.rowCount-1)
}

func (s ShelfRack) SCAD(params map[string]interface{}, detail Detail) (string, error) {
	l, err := shelfRackParamsToLayout(params)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// generated by reef-site generate.ShelfRack %s — do not hand-edit\n", s.Version())
	fmt.Fprintf(&b, "$fn = %d;\n\n", detail.fn())
	fmt.Fprintf(&b, "width_mm = %s;\n", fnum(l.widthMm))
	fmt.Fprintf(&b, "depth_mm = %s;\n", fnum(l.depthMm))
	fmt.Fprintf(&b, "deck_thickness_mm = %s;\n", fnum(shelfDeckThicknessMm))
	fmt.Fprintf(&b, "leg_height_mm = %s;\n", fnum(l.legHeightMm))
	fmt.Fprintf(&b, "leg_size_mm = %s;\n", fnum(shelfLegSizeMm))
	fmt.Fprintf(&b, "leg_edge_offset_mm = %s;\n", fnum(shelfLegEdgeOffsetMm))
	fmt.Fprintf(&b, "plug_hole_d = %s;\n", fnum(l.plugHoleDiameterMm))
	fmt.Fprintf(&b, "col_edge_margin_mm = %s;\n", fnum(l.colEdgeMarginMm))
	fmt.Fprintf(&b, "row_edge_margin_mm = %s;\n", fnum(l.rowEdgeMarginMm))
	fmt.Fprintf(&b, "holes_per_row = %d;\n", l.holesPerRow)
	fmt.Fprintf(&b, "row_count = %d;\n\n", l.rowCount)

	b.WriteString(shelfRackSCADBody)
	return b.String(), nil
}

// Analyze computes structural facts analytically from the same layout math
// SCAD() uses — see the Module.Analyze doc comment for why this doesn't
// inspect the mesh.
func (s ShelfRack) Analyze(params map[string]interface{}) (Analysis, error) {
	l, err := shelfRackParamsToLayout(params)
	if err != nil {
		return Analysis{}, err
	}

	minWall := shelfDeckThicknessMm

	if l.holesPerRow > 1 {
		colWall := l.holeSpacingXMm() - l.plugHoleDiameterMm
		minWall = math.Min(minWall, colWall)
	}
	if l.rowCount > 1 {
		rowWall := l.holeSpacingYMm() - l.plugHoleDiameterMm
		minWall = math.Min(minWall, rowWall)
	}

	return Analysis{
		MinWallMm:         minWall,
		HasInternalCavity: false, // holes go straight through and legs are solid — no blind cavity at all
		SealedVoid:        false,
	}, nil
}

// ShelfRackMaxHolesPerRow is the width-axis analog of
// FragRackMaxHolesPerTier — exposed so the API/frontend derived-bounds can
// recompute and clamp holesPerRow the same way the generator will interpret
// it.
func ShelfRackMaxHolesPerRow(widthMm, plugHoleDiameterMm float64) int {
	return maxCountForSpan(widthMm, plugHoleDiameterMm)
}

// ShelfRackMaxRows is the same packing math applied along the depth axis —
// deliberately a separate exported function (rather than one generic helper
// called from both the width and depth schema fields) so the frontend's
// per-field derived-bound mirror stays a direct 1:1 name match with its Go
// counterpart.
func ShelfRackMaxRows(depthMm, plugHoleDiameterMm float64) int {
	return maxCountForSpan(depthMm, plugHoleDiameterMm)
}

func maxCountForSpan(spanMm, plugHoleDiameterMm float64) int {
	edgeMargin := plugHoleDiameterMm/2 + shelfMinEdgeWallMm
	usable := spanMm - 2*edgeMargin
	if usable <= 0 {
		return 1
	}
	minSpacing := plugHoleDiameterMm + shelfMinEdgeWallMm
	max := int(math.Floor(usable/minSpacing)) + 1
	if max < 1 {
		max = 1
	}
	return max
}

// ValidateParams catches a holesPerRow/rowCount that packs tighter than
// ShelfRackMaxHolesPerRow/ShelfRackMaxRows allow for the given
// width/depth/hole-diameter — same reasoning as FragRack.ValidateParams:
// the schema's static min/max can't express that the real limit depends on
// other fields' current values.
func (s ShelfRack) ValidateParams(params map[string]interface{}) error {
	l, err := shelfRackParamsToLayout(params)
	if err != nil {
		return err
	}
	if max := ShelfRackMaxHolesPerRow(l.widthMm, l.plugHoleDiameterMm); l.holesPerRow > max {
		return fmt.Errorf(
			"holesPerRow %d is too many for a %.0fmm-wide deck with %.0fmm plug holes — %d is the most that fit with a safe wall between them. Reduce holes per row or increase width.",
			l.holesPerRow, l.widthMm, l.plugHoleDiameterMm, max,
		)
	}
	if max := ShelfRackMaxRows(l.depthMm, l.plugHoleDiameterMm); l.rowCount > max {
		return fmt.Errorf(
			"rowCount %d is too many for a %.0fmm-deep deck with %.0fmm plug holes — %d is the most that fit with a safe wall between them. Reduce rows or increase depth.",
			l.rowCount, l.depthMm, l.plugHoleDiameterMm, max,
		)
	}
	return nil
}

// shelfRackSCADBody is the fixed CSG program; every dimension is a variable
// assigned above so the geometry is entirely parametric. The deck's hole
// cutouts are unioned before the single subtraction against the solid deck,
// same batching reasoning as FragRack's inner_rack(). Legs extrude straight
// up from the deck's top face so the part prints flat, on its back face,
// without supports.
const shelfRackSCADBody = `
module shelf_leg(x, y) {
    translate([x, y, deck_thickness_mm])
        cube([leg_size_mm, leg_size_mm, leg_height_mm]);
}

module shelf_deck() {
    difference() {
        cube([width_mm, depth_mm, deck_thickness_mm]);

        union() {
            for (r = [0 : row_count - 1]) {
                row_spacing = row_count > 1
                    ? (depth_mm - 2 * row_edge_margin_mm) / (row_count - 1)
                    : 0;
                row_y = row_count > 1
                    ? row_edge_margin_mm + r * row_spacing
                    : depth_mm / 2;
                col_spacing = holes_per_row > 1
                    ? (width_mm - 2 * col_edge_margin_mm) / (holes_per_row - 1)
                    : 0;
                for (c = [0 : holes_per_row - 1]) {
                    col_x = holes_per_row > 1
                        ? col_edge_margin_mm + c * col_spacing
                        : width_mm / 2;
                    translate([col_x, row_y, -0.5])
                        cylinder(d = plug_hole_d, h = deck_thickness_mm + 1);
                }
            }
        }
    }
}

shelf_deck();
shelf_leg(leg_edge_offset_mm, leg_edge_offset_mm);
shelf_leg(width_mm - leg_edge_offset_mm - leg_size_mm, leg_edge_offset_mm);
shelf_leg(leg_edge_offset_mm, depth_mm - leg_edge_offset_mm - leg_size_mm);
shelf_leg(width_mm - leg_edge_offset_mm - leg_size_mm, depth_mm - leg_edge_offset_mm - leg_size_mm);
`
