version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=poltergeist
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local