package trivai

import (
	"fmt"
)

var (
	promptDelimiter   = ":::"
	categoryDelimiter = "---"
	dash              = "-"
)

func template() string {
	return fmt.Sprintf("%squestion%scategory%s", promptDelimiter, categoryDelimiter, promptDelimiter)
}

func questionsPrompt() string {
	return fmt.Sprintf(
		"Can you please generate six difficult trivia questions for me. Interpolate them into this template: \":::{prompt}---{category}---{answer}:::\". Don't include any numbers, quotations or newlines in your response.",
	)
}

func gradePrompt(question string, answer string) string {
	return fmt.Sprintf(
		`Given the question "%s", would you consider the answer "%s" correct, allowing for misspellings, and only requiring the last name if the answer is a person? If correct, reply with only "true". If not correct, reply with only "false."`,
		question,
		answer,
	)
}

func howManyQuestionPrompt(promptString string) string {
	return fmt.Sprintf("Can you please generate a trivia question in which someone has to guess how many of something exists? %s Please respond with the question, followed by three colons, followed by the answer as a number, followed by three colons, follow by a bit of flavor text to explain why the number is what it is.", promptString)
}

var PromptSeeds = []string{
	"Make the question about the number of stars in the Milky Way galaxy",
	"Make the question about the total length of the Great Wall of China in kilometers",
	"Make the question about the number of bones in the adult human body",
	"Make the question about the total number of languages spoken worldwide",
	"Make the question about the depth of the Mariana Trench in meters",
	"Make the question about the number of countries in the world",
	"Make the question about the height of Mount Everest in meters",
	"Make the question about the number of elements in the periodic table",
	"Make the question about the total population of Tokyo",
	"Make the question about the number of keys on a grand piano",
	"Make the question about the distance from Earth to the Moon in kilometers",
	"Make the question about the number of paintings Vincent van Gogh sold during his lifetime",
	"Make the question about the total number of species of birds in the world",
	"Make the question about the length of the Nile River in kilometers",
	"Make the question about the number of heartbeats per minute of a hummingbird",
	"Make the question about the total number of books in the Library of Congress",
	"Make the question about the number of active volcanoes in the world",
	"Make the question about the depth of the deepest dive by a whale in meters",
	"Make the question about the number of moons orbiting Jupiter",
	"Make the question about the total number of chess grandmasters in the world",
	"Make the question about the number of steps in the Eiffel Tower",
	"Make the question about the total area of the Sahara Desert in square kilometers",
	"Make the question about the number of episodes in the original 'Star Trek' series",
	"Make the question about the length of the Amazon River in kilometers",
	"Make the question about the number of countries that use the euro as their currency",
	"Make the question about the total number of Nobel Prize categories",
	"Make the question about the number of muscles in the human body",
	"Make the question about the total number of planets in the Solar System",
	"Make the question about the number of signatures on the US Declaration of Independence",
	"Make the question about the total number of islands in the Philippines",
	// Continue with similar prompts for a total of 365 strings
	"Make the question about the number of planets discovered outside our Solar System",
	"Make the question about the total number of episodes in 'The Simpsons'",
	"Make the question about the number of bones in a giraffe's neck",
	"Make the question about the total number of Harry Potter books published",
	"Make the question about the depth of Lake Baikal in meters",
	"Make the question about the number of symphonies composed by Beethoven",
	"Make the question about the total number of countries in Africa",
	"Make the question about the height of the Burj Khalifa in meters",
	"Make the question about the number of official languages in India",
	"Make the question about the total number of Olympic Games held",
	"Make the question about the number of moons orbiting Mars",
	"Make the question about the total length of the Amazon River in kilometers",
	"Make the question about the number of elements discovered by Marie Curie",
	"Make the question about the total number of paintings made by Pablo Picasso",
	"Make the question about the number of keys on a standard piano",
	"Make the question about the total number of Shakespeare's plays",
	"Make the question about the number of countries that border China",
	"Make the question about the total area of the Pacific Ocean in square kilometers",
	"Make the question about the number of human chromosomes",
	"Make the question about the total number of stars in the Andromeda Galaxy",
	"Make the question about the number of teeth in an adult human mouth",
	"Make the question about the total number of moons orbiting Saturn",
	"Make the question about the length of the Great Barrier Reef in kilometers",
	"Make the question about the number of wonders in the ancient world",
	"Make the question about the total number of playable characters in 'Super Smash Bros. Ultimate'",
	"Make the question about the number of lines in a sonnet",
	"Make the question about the total number of heart chambers in a frog",
	"Make the question about the number of states in the United States",
	"Make the question about the total number of elements in the periodic table as of 2021",
	"Make the question about the number of goals scored by Pelé in official matches",
	"Make the question about the total number of episodes in 'Friends'",
	"Make the question about the number of provinces in Canada",
	"Make the question about the total number of bones in a shark's body",
	"Make the question about the number of time zones in Russia",
	"Make the question about the total number of Nobel laureates as of 2021",
	"Make the question about the number of official languages of the United Nations",
	"Make the question about the total number of planets in the Solar System including dwarf planets",
	"Make the question about the number of players on a soccer team",
	"Make the question about the total number of chess pieces on a board at the start of a game",
	"Make the question about the number of wonders in the modern world",
	// Continue with similar prompts for a total of 365 strings
	"Make the question about the number of moons orbiting Jupiter",
	"Make the question about the total number of chess grandmasters worldwide",
	"Make the question about the length of the Nile River in kilometers",
	"Make the question about the number of elements in the periodic table that are gases at room temperature",
	"Make the question about the total number of countries in the world",
	"Make the question about the number of paintings attributed to Vincent van Gogh",
	"Make the question about the total number of languages spoken in the world",
	"Make the question about the number of countries in the European Union",
	"Make the question about the total number of species of birds known to science",
	"Make the question about the number of human genes",
	"Make the question about the total number of active volcanoes on Earth",
	"Make the question about the number of stars in the Milky Way",
	"Make the question about the total number of historical emperors of Rome",
	"Make the question about the number of bones in the human adult body",
	"Make the question about the total number of Olympic sports",
	"Make the question about the number of wonders in the new world",
	"Make the question about the total number of books in the Old Testament",
	"Make the question about the number of permanent members of the United Nations Security Council",
	"Make the question about the total number of sonnets written by William Shakespeare",
	"Make the question about the number of keys on a grand piano",
	"Make the question about the total number of countries that have landed on the moon",
	"Make the question about the number of heart chambers in a mammal",
	"Make the question about the total number of artificial satellites orbiting Earth",
	"Make the question about the number of continents on Earth",
	"Make the question about the total number of elements discovered so far",
	"Make the question about the number of official sports in the Winter Olympics",
	"Make the question about the total number of time zones across the world",
	"Make the question about the number of lines in a haiku",
	"Make the question about the total number of seats in the United Nations General Assembly",
	"Make the question about the number of planets in the Milky Way capable of supporting life",
	"Make the question about the total number of pharaohs in ancient Egypt",
	"Make the question about the number of chapters in the Quran",
	"Make the question about the total number of islands in Indonesia",
	"Make the question about the number of muscles used to take a step",
	"Make the question about the total number of atoms in a human cell",
	"Make the question about the number of symphonies composed by Mozart",
	"Make the question about the total number of dog breeds recognized by the American Kennel Club",
	"Make the question about the number of bricks in the Great Wall of China",
	"Make the question about the total number of UNESCO World Heritage Sites",
	"Make the question about the number of playable characters in 'Mario Kart 8 Deluxe'",
	"Make the question about the total number of teeth in a shark's mouth",
	"Make the question about the number of countries that have a female head of state",
	"Make the question about the total number of apps available in the Apple App Store",
	"Make the question about the number of verses in the Bible",
	"Make the question about the total number of species of dinosaurs discovered",
	"Make the question about the number of moons orbiting Venus",
	"Make the question about the total number of active users on Facebook",
	"Make the question about the number of public holidays in the United States",
	"Make the question about the total number of chess openings recognized by FIDE",
	"Make the question about the number of bones in a cat's body",
	"Make the question about the total number of episodes in 'Game of Thrones'",
	"Make the question about the number of countries in Antarctica",
	"Make the question about the total number of miles the Amazon River stretches",
	"Make the question about the number of elements that make up the human DNA",
	"Make the question about the total number of players in an American football team",
	"Make the question about the number of official languages in the European Union",
	"Make the question about the total number of planets discovered by the Hubble Space Telescope",
	"Make the question about the number of Nobel Prizes awarded to Albert Einstein",
	"Make the question about the total number of species of fish in the ocean",
	"Make the question about the number of amendments in the US Constitution",
	"Make the question about the total number of operas composed by Verdi",
	"Make the question about the number of strokes in the Chinese character for 'dragon'",
	"Make the question about the total number of countries that participated in the first modern Olympics",
	"Make the question about the number of moons orbiting Pluto",
	"Make the question about the total number of players on a baseball team",
	"Make the question about the number of countries in South America",
	"Make the question about the total number of Harry Potter movies released",
	"Make the question about the number of faces on a standard dice",
	"Make the question about the total number of lines in 'The Iliad'",
	"Make the question about the number of planets discovered by Galileo",
	"Make the question about the total number of muscles in a cat's ear",
	"Make the question about the number of elements that are liquids at room temperature",
	"Make the question about the total number of countries in Asia",
	"Make the question about the number of official languages in Switzerland",
	"Make the question about the total number of bones in a bird's wing",
	"Make the question about the number of days in a leap year",
	"Make the question about the total number of paintings in the Louvre",
	"Make the question about the number of countries that have nuclear weapons",
	"Make the question about the total number of species of mammals in the world",
	"Make the question about the number of players in a rugby team",
	"Make the question about the total number of moons orbiting Uranus",
	"Make the question about the length of the Great Wall of China in miles",
	"Make the question about the number of chambers in the human heart",
	"Make the question about the total number of episodes in 'Breaking Bad'",
	"Make the question about the number of countries in the United Nations",
	"Make the question about the total number of elements that are metals",
	"Make the question about the number of Grand Slam titles won by Serena Williams",
	"Make the question about the total number of books in the New Testament",
	"Make the question about the number of planets in the known universe",
	"Make the question about the total number of species of plants in the Amazon rainforest",
	"Make the question about the number of keys on a standard accordion",
	"Make the question about the total number of languages written from right to left",
	"Make the question about the number of countries that have legalized same-sex marriage",
	"Make the question about the total number of stars in the observable universe",
	"Make the question about the number of bones in a snake's body",
	"Make the question about the total number of countries in the European Free Trade Association",
	"Make the question about the number of moons orbiting Earth",
	"Make the question about the total number of species of bees",
	"Make the question about the number of letters in the Greek alphabet",
	"Make the question about the total number of phobias recognized by psychologists",
	"Make the question about the number of elements named after scientists",
	"Make the question about the total number of countries that have hosted the Summer Olympics",
	"Make the question about the number of symphonies composed by Brahms",
	"Make the question about the total number of islands in the Maldives",
	"Make the question about the number of states in India",
	"Make the question about the total number of muscles in the human face",
	"Make the question about the number of planets discovered by the Kepler Space Telescope",
	"Make the question about the total number of species of birds in the Amazon rainforest",
	"Make the question about the number of countries that border the Mediterranean Sea",
	"Make the question about the total number of episodes in 'Seinfeld'",
	"Make the question about the number of bones in a human foot",
	"Make the question about the total number of languages in the world recognized by the United Nations",
	"Make the question about the number of wonders in the medieval world",
	"Make the question about the total number of countries in North America",
	"Make the question about the number of elements that are solid at room temperature",
	"Make the question about the total number of moons orbiting Neptune",
	"Make the question about the number of countries in the African Union",
	"Make the question about the total number of species of reptiles known to science",
	"Make the question about the number of lines in a Shakespearean play",
	"Make the question about the total number of countries that have a monarchy",
	"Make the question about the number of official languages in South Africa",
	"Make the question about the total number of bones in a human hand",
	"Make the question about the number of countries that have won the FIFA World Cup",
	"Make the question about the total number of species of cacti",
	"Make the question about the number of moons orbiting Mercury",
	"Make the question about the total number of Nobel Prizes given out as of the current year",
	"Make the question about the number of countries in Oceania",
	"Make the question about the total number of species of spiders",
	"Make the question about the number of elements that are radioactive",
	"Make the question about the total number of countries in the Commonwealth of Nations",
	"Make the question about the number of official languages in the United Nations",
	"Make the question about the total number of species of fungi known to science",
	"Make the question about the number of countries that use the metric system",
	"Make the question about the total number of planets in the Andromeda Galaxy",
	"Make the question about the number of bones in a human skull",
	"Make the question about the total number of species of ants",
	"Make the question about the number of countries that have a flag with more than three colors",
	"Make the question about the total number of episodes in 'The Office' (US version)",
	"Make the question about the number of elements that can exist in a plasma state",
	"Make the question about the total number of species of trees in the Amazon rainforest",
	"Make the question about the number of countries that have a population exceeding 100 million",
	"Make the question about the total number of moons orbiting Jupiter",
	"Make the question about the number of official languages in Canada",
	"Make the question about the total number of species of mammals discovered in the last decade",
	"Make the question about the number of bones in a bat's wing",
	"Make the question about the total number of countries that have a red color in their flag",
	"Make the question about the number of elements that are nonmetals",
	"Make the question about the total number of species of birds that are flightless",
	"Make the question about the number of countries in the European Economic Area",
	"Make the question about the total number of species of coral in the Great Barrier Reef",
	"Make the question about the number of moons orbiting Uranus",
	"Make the question about the total number of species of fish in the Amazon River",
	"Make the question about the number of countries that have a coastline on the Atlantic Ocean",
	"Make the question about the total number of elements in the periodic table that are synthetic",
	"Make the question about the number of official languages in Nigeria",
	"Make the question about the total number of species of mammals in Africa",
	"Make the question about the number of bones in a human ear",
	"Make the question about the total number of countries in the League of Arab States",
	"Make the question about the number of elements that are halogens",
	"Make the question about the total number of species of plants in the Sahara Desert",
	"Make the question about the number of countries that have a green color in their flag",
	"Make the question about the total number of species of birds in North America",
	"Make the question about the number of moons orbiting Saturn",
	"Make the question about the total number of species of fish in the Pacific Ocean",
	"Make the question about the number of countries that have a population under 1 million",
	"Make the question about the total number of elements in the periodic table that are noble gases",
	"Make the question about the number of official languages in the European Parliament",
	"Make the question about the total number of species of mammals in the Arctic",
	"Make the question about the number of bones in a bird's body",
	"Make the question about the total number of countries that have a blue color in their flag",
	"Make the question about the number of elements that are metals",
	"Make the question about the number of satellites orbiting Earth",
	"Make the question about the total number of active users on Facebook",
	"Make the question about the number of symphonies composed by Beethoven",
	"Make the question about the total number of languages listed in the Ethnologue",
	"Make the question about the number of countries that have legalized same-sex marriage",
	"Make the question about the total number of Olympic Games held to date",
	"Make the question about the number of planets in our solar system",
	"Make the question about the total number of UNESCO World Heritage Sites",
	"Make the question about the number of bones in the human body",
	"Make the question about the total number of Harry Potter books published",
	"Make the question about the number of time zones in Russia",
	"Make the question about the total number of elements discovered so far",
	"Make the question about the number of continents on Earth",
	"Make the question about the total number of countries in the United Nations",
	"Make the question about the number of natural satellites orbiting Mars",
	"Make the question about the total number of dog breeds recognized by the AKC",
	"Make the question about the number of lines in a sonnet",
	"Make the question about the total number of people who have walked on the Moon",
	"Make the question about the number of keys on a standard piano",
	"Make the question about the total number of apps available in the Apple App Store",
	"Make the question about the number of wonders in the ancient world",
	"Make the question about the total number of human genes",
	"Make the question about the number of stars in the observable universe",
	"Make the question about the total number of species of dinosaurs discovered",
	"Make the question about the number of seats in the United States Senate",
	"Make the question about the total number of episodes in 'Friends'",
	"Make the question about the number of countries in Africa",
	"Make the question about the total number of atoms in a human cell",
	"Make the question about the number of amendments in the US Constitution",
	"Make the question about the total number of players in a soccer team",
	"Make the question about the number of strokes in the Chinese character for 'biáng'",
	"Make the question about the total number of chess pieces on a board at the start of a game",
	"Make the question about the number of hearts an octopus has",
	"Make the question about the total number of muscles in the human body",
	"Make the question about the number of states in the United States",
	"Make the question about the total number of teeth in an adult human mouth",
	"Make the question about the number of countries that border China",
	"Make the question about the total number of verses in the Quran",
	"Make the question about the number of eyes a spider has",
	"Make the question about the total number of bones in a cat's body",
	"Make the question about the number of days in a leap year",
	"Make the question about the total number of islands in the Philippines",
	"Make the question about the number of letters in the Greek alphabet",
	"Make the question about the total number of paintings created by Picasso",
	"Make the question about the number of players on an American football team",
	"Make the question about the total number of sonnets written by Shakespeare",
	"Make the question about the number of moons orbiting Pluto",
	"Make the question about the total number of countries in South America",
	"Make the question about the number of official languages in Switzerland",
	"Make the question about the total number of Nobel laureates",
	"Make the question about the number of bricks in the Great Pyramid of Giza",
	"Make the question about the total number of species of birds",
	"Make the question about the number of chambers in the human heart",
	"Make the question about the total number of public holidays in Japan",
	"Make the question about the number of provinces in Canada",
	"Make the question about the total number of stars in the Milky Way",
	"Make the question about the number of stripes on the US flag",
	"Make the question about the total number of books in the New Testament",
	"Make the question about the number of planets discovered outside our solar system",
	"Make the question about the total number of pharaohs in ancient Egypt",
	"Make the question about the number of symphonies composed by Mozart",
	"Make the question about the total number of plays written by Shakespeare",
	"Make the question about the number of faces on a standard dice",
	"Make the question about the total number of countries that have a monarchy",
	"Make the question about the number of bones in a shark's body",
	"Make the question about the total number of languages in India",
	"Make the question about the number of gates in Jerusalem's Old City walls",
	"Make the question about the total number of islands in Indonesia",
	"Make the question about the number of disciples Jesus had",
	"Make the question about the total number of volcanoes in Hawaii",
	"Make the question about the number of cantons in Switzerland",
	"Make the question about the total number of species of bees",
	"Make the question about the number of lines in a haiku",
	"Make the question about the total number of countries that have a female head of state",
	"Make the question about the number of elements that are gases at room temperature",
	"Make the question about the total number of historical periods in Japanese history",
	"Make the question about the number of planets in the Star Wars galaxy",
	"Make the question about the total number of missions to Mars",
	"Make the question about the number of wonders of the modern world",
	"Make the question about the total number of operas composed by Verdi",
	"Make the question about the number of bones in a giraffe's neck",
	"Make the question about the total number of countries in the world that do not have a river",
	"Make the question about the number of years in a century",
	"Make the question about the total number of species of fish in the ocean",
	"Make the question about the number of keys on a standard computer keyboard",
	"Make the question about the total number of phobias recognized by psychologists",
	"Make the question about the number of moons orbiting Venus",
	"Make the question about the total number of elements that were artificially created",
	"Make the question about the number of days in a year on Mars",
	"Make the question about the total number of human chromosomes",
	"Make the question about the number of countries in the Arctic Circle",
	"Make the question about the total number of words in the English language",
	"Make the question about the number of countries that have nuclear weapons",
	"Make the question about the total number of Shakespearean sonnets",
	"Make the question about the number of years Nelson Mandela spent in prison",
	"Make the question about the total number of countries in Asia",
	"Make the question about the number of moons orbiting Earth",
	"Make the question about the total number of species of reptiles",
	"Make the question about the number of countries that have a unicameral legislature",
	"Make the question about the total number of muscles used to smile",
	"Make the question about the number of elements in the human body",
	"Make the question about the total number of islands in the Maldives",
	"Make the question about the number of countries that have hosted the Olympics",
	"Make the question about the total number of species of amphibians",
	"Make the question about the number of time zones in the world",
	"Make the question about the total number of books in the Harry Potter series",
	"Make the question about the number of countries in the European Union",
	"Make the question about the total number of species of plants",
	"Make the question about the number of letters in the longest word in the English language",
	"Make the question about the total number of countries that have a desert",
	"Make the question about the number of bones in a snake's body",
	"Make the question about the total number of languages spoken in India",
	"Make the question about the number of countries that have a border with Russia",
	"Make the question about the total number of species of birds that can fly",
	"Make the question about the number of planets that can support life as we know it",
	"Make the question about the total number of countries in Africa that are landlocked",
	"Make the question about the number of elements that are liquids at room temperature",
	"Make the question about the total number of species of mammals",
	"Make the question about the number of countries that are members of the United Nations",
	"Make the question about the total number of species of insects",
	"Make the question about the number of days in February during a leap year",
	"Make the question about the total number of moons in our solar system",
	"Make the question about the number of continents that contain a desert",
	"Make the question about the total number of human senses",
	"Make the question about the number of countries that have a red color in their national flag",
	"Make the question about the total number of species of marine life",
	"Make the question about the number of countries in the world that are island nations",
	"Make the question about the total number of species of fungi",
	"Make the question about the number of states in India",
	"Make the question about the total number of planets in the Milky Way galaxy",
	"Make the question about the number of official languages in India",
	"Make the question about the total number of species of coral in the ocean",
	"Make the question about the number of countries that have a population over 1 billion",
	"Make the question about the total number of species of birds that are endangered",
	"Make the question about the number of bones in a human foot",
	"Make the question about the total number of countries that have a monarchy",
	"Make the question about the number of elements that are solid at room temperature",
	"Make the question about the total number of species of plants that are carnivorous",
	"Make the question about the number of countries in the world that have a coastline",
	"Make the question about the total number of species of animals discovered in the last year",
	"Make the question about the number of moons orbiting Neptune",
	"Make the question about the total number of species of birds in the Amazon rainforest",
	"Make the question about the number of countries in the Commonwealth",
	"Make the question about the total number of species of marine mammals",
	"Make the question about the number of official languages in the European Union",
	"Make the question about the total number of species of trees worldwide",
	"Make the question about the number of countries that have a blue color in their national flag",
	"Make the question about the total number of species of bacteria known to science",
	"Make the question about the number of elements in the periodic table",
	"Make the question about the total number of species of animals in the world",
	"Make the question about the number of countries that have a population under 500,000",
	"Make the question about the total number of species of birds that migrate",
	"Make the question about the number of countries in North America",
	"Make the question about the total number of species of fish in the world's oceans",
}
