package locationseeder

import (
	"fmt"

	"github.com/MaxBlaushild/poltergeist/pkg/googlemaps"
	"github.com/MaxBlaushild/poltergeist/pkg/models"
	"github.com/google/uuid"
)

func (c *client) mapTypeToTag(t googlemaps.PlaceType) (*models.Tag, error) {
	switch t {
	case googlemaps.TypeAccounting:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "accounting",
		}, nil
	case googlemaps.TypeAirport:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "airport",
		}, nil
	case googlemaps.TypeAmusementPark:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "amusement_park",
		}, nil
	case googlemaps.TypeAquarium:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "aquarium",
		}, nil
	case googlemaps.TypeArtGallery:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "art_gallery",
		}, nil
	case googlemaps.TypeAtm:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "atm",
		}, nil
	case googlemaps.TypeBakery:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "bakery",
		}, nil
	case googlemaps.TypeBank:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "bank",
		}, nil
	case googlemaps.TypeBar:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "bar",
		}, nil
	case googlemaps.TypeBeautySalon:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "beauty_salon",
		}, nil
	case googlemaps.TypeBicycleStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "bicycle_store",
		}, nil
	case googlemaps.TypeBookStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "book_store",
		}, nil
	case googlemaps.TypeBowlingAlley:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "bowling_alley",
		}, nil
	case googlemaps.TypeBusStation:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "bus_station",
		}, nil
	case googlemaps.TypeCafe:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "cafe",
		}, nil
	case googlemaps.TypeCampground:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "campground",
		}, nil
	case googlemaps.TypeCarDealer:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "car_dealer",
		}, nil
	case googlemaps.TypeCarRental:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "car_rental",
		}, nil
	case googlemaps.TypeCarRepair:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "car_repair",
		}, nil
	case googlemaps.TypeCarWash:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "car_wash",
		}, nil
	case googlemaps.TypeCasino:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "casino",
		}, nil
	case googlemaps.TypeCemetery:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "cemetery",
		}, nil
	case googlemaps.TypeChurch:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "church",
		}, nil
	case googlemaps.TypeCityHall:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "city_hall",
		}, nil
	case googlemaps.TypeClothingStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "clothing_store",
		}, nil
	case googlemaps.TypeConvenienceStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "convenience_store",
		}, nil
	case googlemaps.TypeCourthouse:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "courthouse",
		}, nil
	case googlemaps.TypeDentist:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "dentist",
		}, nil
	case googlemaps.TypeDepartmentStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "department_store",
		}, nil
	case googlemaps.TypeDoctor:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "doctor",
		}, nil
	case googlemaps.TypeDrugstore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "drugstore",
		}, nil
	case googlemaps.TypeElectrician:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "electrician",
		}, nil
	case googlemaps.TypeElectronicsStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "electronics_store",
		}, nil
	case googlemaps.TypeEmbassy:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "embassy",
		}, nil
	case googlemaps.TypeFireStation:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "fire_station",
		}, nil
	case googlemaps.TypeFlorist:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "florist",
		}, nil
	case googlemaps.TypeFuneralHome:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "funeral_home",
		}, nil
	case googlemaps.TypeFurnitureStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "furniture_store",
		}, nil
	case googlemaps.TypeGasStation:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "gas_station",
		}, nil
	case googlemaps.TypeGym:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "gym",
		}, nil
	case googlemaps.TypeHairCare:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "hair_care",
		}, nil
	case googlemaps.TypeHardwareStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "hardware_store",
		}, nil
	case googlemaps.TypeHinduTemple:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "hindu_temple",
		}, nil
	case googlemaps.TypeHomeGoodsStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "home_goods_store",
		}, nil
	case googlemaps.TypeHospital:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "hospital",
		}, nil
	case googlemaps.TypeInsuranceAgency:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "insurance_agency",
		}, nil
	case googlemaps.TypeJewelryStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "jewelry_store",
		}, nil
	case googlemaps.TypeLaundry:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "laundry",
		}, nil
	case googlemaps.TypeLawyer:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "lawyer",
		}, nil
	case googlemaps.TypeLibrary:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "library",
		}, nil
	case googlemaps.TypeLightRailStation:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "light_rail_station",
		}, nil
	case googlemaps.TypeLiquorStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "liquor_store",
		}, nil
	case googlemaps.TypeLocalGovernmentOffice:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "local_government_office",
		}, nil
	case googlemaps.TypeLocksmith:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "locksmith",
		}, nil
	case googlemaps.TypeLodging:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "lodging",
		}, nil
	case googlemaps.TypeMealDelivery:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "meal_delivery",
		}, nil
	case googlemaps.TypeMealTakeaway:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "meal_takeaway",
		}, nil
	case googlemaps.TypeMosque:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "mosque",
		}, nil
	case googlemaps.TypeMovieRental:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "movie_rental",
		}, nil
	case googlemaps.TypeMovieTheater:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "movie_theater",
		}, nil
	case googlemaps.TypeMovingCompany:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "moving_company",
		}, nil
	case googlemaps.TypeMuseum:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "museum",
		}, nil
	case googlemaps.TypeNightClub:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "night_club",
		}, nil
	case googlemaps.TypePainter:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "painter",
		}, nil
	case googlemaps.TypePark:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "park",
		}, nil
	case googlemaps.TypeParking:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "parking",
		}, nil
	case googlemaps.TypePetStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "pet_store",
		}, nil
	case googlemaps.TypePharmacy:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "pharmacy",
		}, nil
	case googlemaps.TypePhysiotherapist:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "physiotherapist",
		}, nil
	case googlemaps.TypePlumber:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "plumber",
		}, nil
	case googlemaps.TypePolice:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "police",
		}, nil
	case googlemaps.TypePostOffice:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "post_office",
		}, nil
	case googlemaps.TypePrimarySchool:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "primary_school",
		}, nil
	case googlemaps.TypeRealEstateAgency:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "real_estate_agency",
		}, nil
	case googlemaps.TypeRestaurant:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "restaurant",
		}, nil
	case googlemaps.TypeRoofingContractor:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "roofing_contractor",
		}, nil
	case googlemaps.TypeRvPark:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "rv_park",
		}, nil
	case googlemaps.TypeSchool:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "school",
		}, nil
	case googlemaps.TypeSecondarySchool:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "secondary_school",
		}, nil
	case googlemaps.TypeShoeStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "shoe_store",
		}, nil
	case googlemaps.TypeShoppingMall:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "shopping_mall",
		}, nil
	case googlemaps.TypeSpa:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "spa",
		}, nil
	case googlemaps.TypeStadium:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "stadium",
		}, nil
	case googlemaps.TypeStorage:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "storage",
		}, nil
	case googlemaps.TypeStore:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "store",
		}, nil
	case googlemaps.TypeSubwayStation:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "subway_station",
		}, nil
	case googlemaps.TypeSupermarket:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "supermarket",
		}, nil
	case googlemaps.TypeSynagogue:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "synagogue",
		}, nil
	case googlemaps.TypeTaxiStand:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "taxi_stand",
		}, nil
	case googlemaps.TypeTouristAttraction:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "tourist_attraction",
		}, nil
	case googlemaps.TypeTrainStation:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "train_station",
		}, nil
	case googlemaps.TypeTransitStation:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "transit_station",
		}, nil
	case googlemaps.TypeTravelAgency:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "travel_agency",
		}, nil
	case googlemaps.TypeUniversity:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "university",
		}, nil
	case googlemaps.TypeVeterinaryCare:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "veterinary_care",
		}, nil
	case googlemaps.TypeZoo:
		return &models.Tag{
			ID:    uuid.New(),
			Value: "zoo",
		}, nil
	}

	return nil, fmt.Errorf("no tag found for type: %s", t)
}
