export type ZoneKind = {
  id: string;
  createdAt: string;
  updatedAt: string;
  slug: string;
  name: string;
  description: string;
  defaultShopkeeperItemTags: string[];
  overlayColor: string;
  patternTileUrl: string;
  patternTilePrompt: string;
  patternTileGenerationStatus: string;
  patternTileGenerationError: string;
  placeCountRatio: number;
  questCountRatio: number;
  monsterCountRatio: number;
  bossEncounterCountRatio: number;
  raidEncounterCountRatio: number;
  inputEncounterCountRatio: number;
  optionEncounterCountRatio: number;
  expositionCountRatio: number;
  treasureChestCountRatio: number;
  healingFountainCountRatio: number;
  shrineCountRatio: number;
  herbalismResourceCountRatio: number;
  miningResourceCountRatio: number;
  resourceCountRatio: number;
};
