package generate

import (
	"fmt"
	"math"
	"strings"
)

// LidClip is the second configurator (R-1.1/R-4.3) — its entire job is to
// prove the Module abstraction generalizes. It shares nothing with FragRack
// except the interface: its own constants, its own SCAD body, registered
// the same way. If that stopped being true, the abstraction would be wrong.
//
// Each clip is a squared C-bracket that slides over the tank rim; the inner
// mouth is chamfered (wide at the front, narrowing toward the back) so it
// self-centers and pinches the mesh/lid between the narrowing lip and the
// rim's top face as it seats — no horizontal overhang, so it prints without
// supports lying on its back wall.
type LidClip struct{}

func (LidClip) Slug() string    { return "lid_clip" }
func (LidClip) Version() string { return "v1" }

const (
	clipWallMm            = 3.0
	clipLengthMm          = 20.0
	clipGripCapMm         = 18.0 // grip depth caps out here even if rim_width_mm is larger
	clipFitToleranceMm    = 0.4  // slight interference fit against the rim
	clipMouthExtraMm      = 0.6
	clipGapBetweenMm      = 6.0
	clipBraceNotchWidthMm = 10.0
)

func (c LidClip) SCAD(params map[string]interface{}, detail Detail) (string, error) {
	rimThicknessMm, err := paramFloat(params, "rimThicknessMm")
	if err != nil {
		return "", err
	}
	rimWidthMm, err := paramFloat(params, "rimWidthMm")
	if err != nil {
		return "", err
	}
	meshThicknessMm, err := paramFloat(params, "meshThicknessMm")
	if err != nil {
		return "", err
	}
	quantityF, err := paramFloat(params, "quantity")
	if err != nil {
		return "", err
	}
	euroBrace, err := paramBool(params, "euroBrace", false)
	if err != nil {
		return "", err
	}

	quantity := int(math.Round(quantityF))
	if quantity < 1 {
		return "", fmt.Errorf("generate/lid_clip: quantity must be >= 1")
	}

	depth := math.Min(rimWidthMm, clipGripCapMm)
	gap := math.Max(rimThicknessMm-clipFitToleranceMm, 1.0)
	totalHeight := clipWallMm*2 + gap
	lipStartX := depth * 0.5
	mouthGap := gap + meshThicknessMm + clipMouthExtraMm

	var b strings.Builder
	fmt.Fprintf(&b, "// generated by reef-site generate.LidClip %s — do not hand-edit\n", c.Version())
	fmt.Fprintf(&b, "$fn = %d;\n\n", detail.fn())
	fmt.Fprintf(&b, "depth = %s;\n", fnum(depth))
	fmt.Fprintf(&b, "wall = %s;\n", fnum(clipWallMm))
	fmt.Fprintf(&b, "gap = %s;\n", fnum(gap))
	fmt.Fprintf(&b, "total_h = %s;\n", fnum(totalHeight))
	fmt.Fprintf(&b, "lip_start_x = %s;\n", fnum(lipStartX))
	fmt.Fprintf(&b, "mouth_gap = %s;\n", fnum(mouthGap))
	fmt.Fprintf(&b, "clip_length = %s;\n", fnum(clipLengthMm))
	fmt.Fprintf(&b, "clip_gap = %s;\n", fnum(clipGapBetweenMm))
	fmt.Fprintf(&b, "quantity = %d;\n", quantity)
	fmt.Fprintf(&b, "euro_brace = %t;\n", euroBrace)
	fmt.Fprintf(&b, "brace_notch_w = %s;\n\n", fnum(clipBraceNotchWidthMm))

	b.WriteString(lidClipSCADBody)
	return b.String(), nil
}

// Analyze: the clip's three walls (bottom/back/top) are always exactly
// clipWallMm regardless of params — only the internal gap they enclose
// varies. There is no enclosed cavity at all (the C-mouth is open on the
// front face by construction), so R-5.3's sealed-void rule never applies to
// this part.
func (c LidClip) Analyze(params map[string]interface{}) (Analysis, error) {
	return Analysis{
		MinWallMm:  clipWallMm,
		SealedVoid: false,
	}, nil
}

const lidClipSCADBody = `
module clip_profile() {
    difference() {
        square([depth, total_h]);
        polygon(points = [
            [0, wall],
            [depth - wall, wall],
            [depth - wall, wall + gap],
            [lip_start_x, wall + gap],
            [0, wall + mouth_gap]
        ]);
    }
}

module one_clip() {
    difference() {
        rotate([-90, 0, 0])
            linear_extrude(height = clip_length)
                clip_profile();

        // Euro-braced tanks (R-4.3): notch the back wall so the clip clears
        // the center support brace instead of fighting it.
        if (euro_brace) {
            translate([depth - wall - 0.5, clip_length / 2 - brace_notch_w / 2, wall])
                cube([wall + 1, brace_notch_w, gap]);
        }
    }
}

for (i = [0 : quantity - 1]) {
    translate([i * (depth + clip_gap), 0, 0])
        one_clip();
}
`
